### ISSUE TITLE
Add support for sendgrid email service

### ISSUE THREAD

**Issue by ravensorb** [dhananshan/Send-Custom-Email#3]
Any thoughts to adding support for using sendgrid as another option?

**Comment by dhananshan** [comment]
> Any thoughts to adding support for using sendgrid as another option?

@ravensorb to add in Sendgrid option we need to do a HTTP post in ajax. you are free to add in the feature. I guess u may need to use the web api V3 version. I haven't tried yet but here is the link for reference.
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
